#ifndef CONSTANTS_H__INCLULDED
#define CONSTANTS_H__INCLULDED


const float CYCLE_TIME_DELAY = 0.020,
SOLENOID_STATE_TIME_DELAY = 0.500,
INTAKE_SPEED = 0.35;

const int NUMBER_OF_JOYSTICKS = 2,
PORT_JOYSTICK_1 = 0,
PORT_JOYSTICK_2 = 1,

AXIS_Y1 = 1,
AXIS_Y2 = 3,
BUTTON_INTAKE_CLAMP = 2,
BUTTON_INTAKE_LEFT_IN = 5,
BUTTON_INTAKE_LEFT_OUT = 7,
BUTTON_INTAKE_RIGHT_IN = 6,
BUTTON_INTAKE_RIGHT_OUT = 8,

BUTTON_ARM = 2,
BUTTON_CLAW = 3,

PORT_LEFT_TALON_1 = 2,
PORT_LEFT_TALON_2 = 3,
PORT_RIGHT_TALON_1 = 0,
PORT_RIGHT_TALON_2 = 1,
PORT_LEFT_INTAKE_TALON = 6,
PORT_RIGHT_INTAKE_TALON = 7,

PORT_1_ARM_SOLENOID = 3,
PORT_2_ARM_SOLENOID = 2,
PORT_1_CLAW_SOLENOID = 5,
PORT_2_CLAW_SOLENOID = 4,
PORT_1_CLAMP_SOLENOID = 0,
PORT_2_CLAMP_SOLENOID = 1;


#endif /* CONSTANTS_H__INCLUDED */
