#ifndef CONSTANTS_H__INCLULDED
#define CONSTANTS_H__INCLULDED


const float CYCLE_TIME_DELAY = 0.020,
SOLENOID_STATE_TIME_DELAY = 0.500,
MACRO_TIME_MULTIPLIER = 1.001;

const int NUMBER_OF_JOYSTICKS = 2,
PORT_JOYSTICK_1 = 0,
PORT_JOYSTICK_2 = 1,

AXIS_Y1 = 1,
AXIS_X2 = 2,

BUTTON_ARM = 2,
BUTTON_CLAW = 3,

PORT_LEFT_TALON_1 = 0,
PORT_LEFT_TALON_2 = 1,
PORT_RIGHT_TALON_1 = 2,
PORT_RIGHT_TALON_2 = 3,

PORT_1_ARM_SOLENOID = 3,
PORT_2_ARM_SOLENOID = 2,
PORT_1_CLAW_SOLENOID = 5,
PORT_2_CLAW_SOLENOID = 4;


#endif /* CONSTANTS_H__INCLUDED */
