// USB
const int PORT_JOYSTICK = 0,

// PWM
PORT_RIGHT_TALON_1 = 1,
PORT_RIGHT_TALON_2 = 2,
PORT_RIGHT_TALON_3 = 3,
PORT_LEFT_TALON_1 = 5,
PORT_LEFT_TALON_2 = 6,
PORT_LEFT_TALON_3 = 7,

// DIO
PORT_1_LIFT_SOLENOID = 0,
PORT_2_LIFT_SOLENOID = 1,
PORT_1_CLAW_SOLENOID = 3,
PORT_2_CLAW_SOLENOID = 4;
